;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Nov 12 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
        ; Write your code here
	MOV AL, 90H	; Mode 0, Port A INPUT, PORT B OUTPUT, PORT C DONT CARE	1001 X00X
	OUT 46H, AL	; SEND CONTROL WORD
	 
ENDLESS:
	IN AL, 40H	; GET VALUE FROM PORT A
	 CMP AL, 80H   ; 1000 0000 COMPARE IF VALUE IF LESS THAN 80H, WHICH MEANS MSB IS 0, AND MORE THAN 80 MEAN MSB IS 1		X111 XXXX
	 JAE L1
	 AND AL, 8FH	;  MASK THE FIRST 4 BIT AND SAVE OTHER 4 BIT 		0111 XXXX    AND     1000 1111
	 SHR AL, 1H	; CORRESPONDS TO DIVIDING BY 2
	 OUT 42H, AL	; SEND THE VALUE TO PORT B
	 JMP L2
L1:
	 AND AL, 0FH	; MASK FIRST 4 BITS AND SAVE OTHER 4 BIT		1111 XXXX    AND     0000 1111
	 SHL AL, 1H	; CORRESPONDS TO MULTIPLYING BY 2
	 OUT 42H, AL	; SEND THE VALUE TO PORT B
L2:	
        JMP ENDLESS

	
CODE    ENDS
        END START